fail_fast: true
repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: poetry --directory backend run black
      language: system
      types: [file, python]
      files: '^(src|tests)/'
    - id: isort
      name: isort
      entry: poetry --directory backend run isort
      language: system
      types: [file, python]
      files: '^(src|tests)/'

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
