version: '3.8'

services:
  backend:
    build: ./backend
    container_name: api
    ports:
      - "8000:80"
    environment:
      - LLAMA_CLOUD_API_KEY=${LLAMA_CLOUD_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped
