[project]
name = "ai-assistant-self-employers-pt"
version = "0.1.0"
description = "AI-Assistant for Self-Employeers in Portugal"
authors = [
    {name = "paty-oliveira",email = "patriciia.mota@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas (>=2.3.1,<3.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
